### ISSUE TITLE
More Player Interactions

### ISSUE THREAD

**Issue by MrSirSquishy** [DenimRed/SimpleMuseum#21]
I'm not one to request things from mods, but I think that the mod should have more player interaction elements.

I was wondering if there could be ways to change Museum Puppets animations depending on certain aspects, like if the player gets within a certain range the animation changes. I was also wondering if the Museum Puppet would be able to look at players, similarly to before the Puppet could turn to face the player if they get close. 
On a different note, I feel like there should be an easier way to control Puppet animations, like a simple command that I could put into a command block so that if I activate the command block, the Animation of a certain Puppet changes, for example I could make a puppet change from happy to sad with a button.  

**Alternatives**
It should be somewhat possible since using commands blocks it's possible to activate when entities are within a certain range. Command: /execute if entity @a[distance=..4] run 

**Additional Context**
I use the mod 'Ryan's Prototypes' to turn the Puppets into interactable NPC's, though I feel like It would be better if this mod included more Player Interactions to allow the Puppets to be more useable in things like mapmaking.

**Comment by DenimRed** [comment]
Good ideas, the first couple (change animation based on range, and moving the head to look at players) would probably be part of the AI update. The command stuff is good too, cleaner tools for that would be very nice to have.

As a temporary workaround in the meantime, you could use the vanilla [/data](https://minecraft.fandom.com/wiki/Commands/data) command to change a puppet's animations by messing with their data.

**Comment by MrSirSquishy** [comment]
awesome, I'll try messing around with /data some more. good luck with development!
