### ISSUE TITLE
When I attempt to select and idle animation my game crashes pls help

### ISSUE THREAD

**Issue by LXIR** [DenimRed/SimpleMuseum#29]
Whenever I try to select an idle animation for my NPC my game crashes.
 Down below is a post of the crash.
I've tried multiple times to fix this issue.

[crash-2022-12-31_10.23.34-client.txt](https://github.com/DenimRed/SimpleMuseum/files/10327826/crash-2022-12-31_10.23.34-client.txt)

**Comment by DenimRed** [comment]
This is caused by GeckoLib having made breaking changes on a minor version.
For now, downgrade your GeckoLib; the version that Simple Museum compiles against is 3.0.57.

**Comment by LXIR** [comment]
downgraded my geckolib, issue is resolved thank you!

**Comment by GodMorduk** [comment]
Any plans to update?
